# Generated by Django 3.2.6 on 2021-08-03 13:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo_task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, default='', max_length=100)),
                ('due', models.DateTimeField(default=datetime.datetime(2021, 8, 3, 13, 29, 7, 446732, tzinfo=utc))),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
