# Generated by Django 3.2.6 on 2021-08-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_task', '0002_taskuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskuser',
            name='due',
        ),
        migrations.RemoveField(
            model_name='taskuser',
            name='username',
        ),
        migrations.AddField(
            model_name='taskuser',
            name='user_mail',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
