# Generated by Django 3.2.6 on 2021-08-04 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_task', '0003_auto_20210804_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskuser',
            old_name='user_mail',
            new_name='email',
        ),
    ]
