# Generated by Django 3.2.6 on 2021-08-05 07:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(blank=True, default='user', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('password', models.CharField(default='1234', max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=10, region=None)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
