# Generated by Django 3.2.6 on 2021-08-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
