# Generated by Django 3.2.6 on 2021-08-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='NewUser',
        ),
    ]
